# -*- coding: utf-8 -*-
"""ULR Shortener - final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uKds98xy2DFUfP0H2UgYHhjd38iY_V5B
"""

pip install pyshorteners

import pyshorteners as sh

data = input("Enter the URL you want to shorten: ")

link = data

s = sh.Shortener()

print(s.tinyurl.short(link))